export default {
  "img-1.jpg": "https://www.instagram.com/purelase.bulgaria/",
  "img-2.jpg": "https://www.instagram.com/purelase.bulgaria/",
  "img-3.jpg": "https://www.instagram.com/purelase.bulgaria/",
  "img-4.jpg": "https://www.instagram.com/p/Bu59APjAEB0/",
  "img-5.jpg": "https://www.instagram.com/purelase.bulgaria/",
  "img-6.jpg": "https://www.instagram.com/purelase.bulgaria/",
  "img-7.jpg": "https://www.instagram.com/purelase.bulgaria/",
  "img-8.jpg": "https://www.instagram.com/p/Brm-yjHA97o/",
  "img-9.jpg": "https://www.instagram.com/p/Bt2yh64AtMD/",
  "img-10.jpg": "https://www.instagram.com/p/Bs3fCCaB6mM/",
  "img-11.jpg": "https://www.instagram.com/p/ByZwa6WAUtI/",
  "img-12.jpg": "https://www.instagram.com/purelase.bulgaria/",
  "img-13.jpg": "https://www.instagram.com/purelase.bulgaria/",
  "img-14.jpg": "https://www.instagram.com/p/BpUhHr9CK30/",
  "img-15.jpg": "https://www.instagram.com/purelase.bulgaria/",
  "img-16.jpg": "https://www.instagram.com/purelase.bulgaria/",
}
